swagger: '2.0'
info:
  version: '1.0'
  title: orders_v1
  description: >
    Collection to test orders_v1 API Proxy

    Consumer: My Tele2 NL

    Provider: TIP; Siebel_NL
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: api.tele2.com:9006
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /nl/v1/oauth_nl/token:
    post:
      description: This API must be used to authenticate the user.
      summary: /v1/oauth_nl/token Get WSO2 auth token - Step 1
      tags:
      - Misc
      operationId: /v1/oauth_nl/token Get WSO2 auth token - Step 1
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: client_id
        in: formData
        required: true
        type: string
        description: This field requires to have client id, this should be requested and provide by appigee/WSO2
      - name: client_secret
        in: formData
        required: true
        type: string
        description: This field requires to have client secret, this should be requested and provide by appigee/WSO2.
      - name: grant_type
        in: formData
        required: true
        type: string
        description: The values that can be send in this field is 'refresh_token' or 'password'.
      - name: username
        in: formData
        required: true
        type: string
        description: This field should contain the username. It is required when the grant type is password.
      - name: password
        in: formData
        required: true
        type: string
        description: This field should contain the password. It is required when the grant type is password.
      - name: X-Api-Key
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/~1v1~1oauthNl~1token get wso2 auth token - step 1response'
          examples:
            application/json:
              uid: 401203
              token_type: bearer
              expires_in: 2400
              refresh_token: 7bcbf7def9e2da21a4bbef6ef546e4
              access_token: 9f421e6e25599c53abdcede3dc35f8
              customer_type: 4G/LTE
              status: 200
              email: anamewpcftjgnsk16s11ptest0011@tele2.com
              role: Consumer
              msisdn: ''
              resellerShopId: ''
              applicationLinks:
              - id: 10313378919
                application: brite:bill
              - id: 10313378918
                application: siebel
              - id: ''
                application: cbs
      security: []
      x-unitTests:
      - request:
          method: POST
          uri: /nl/v1/oauth_nl/token
          headers:
            Content-Type: application/x-www-form-urlencoded
            X-Api-Key: OUGIuUc9RpSDTocY97cMbcqACdTVAPTu
          body: client_id=DD1hEBiTeEfoP4jjXSraecgMa4wa&client_secret=mclN7iVfJ7PnGB4Ev8HmdCM1zwAa&grant_type=password&username=anamewpcftjgnsk16s11ptest0011@tele2.com&password=Test1234!
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: RAW
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers:
            Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction
            Access-Control-Allow-Methods: DELETE,POST,PUT,GET
            Access-Control-Allow-Origin: '*'
            Cache-Control: no-cache, no-store, max-age=0, must-revalidate
            Connection: keep-alive
            Content-Type: application/json
            Date: Tue, 14 Nov 2017 14:43:44 GMT
            Expires: 0
            Pragma: no-cache
            Server: WSO2-PassThrough-HTTP
            Transfer-Encoding: chunked
            X-Application-Context: application:uat:6060
            X-Content-Type-Options: nosniff
            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
          body: "{\n    \"uid\": \"401203\",\n    \"token_type\": \"bearer\",\n    \"expires_in\": \"2400\",\n    \"refresh_token\": \"7bcbf7def9e2da21a4bbef6ef546e4\",\n    \"access_token\": \"9f421e6e25599c53abdcede3dc35f8\",\n    \"customer_type\": \"4G/LTE\",\n    \"status\": \"200\",\n    \"email\": \"anamewpcftjgnsk16s11ptest0011@tele2.com\",\n	\"role\": \"Consumer\",\n    \"msisdn\": \"\",\n    \"resellerShopId\": \"\",\n	\"applicationLinks\": [\n		{\n			\"id\": \"10313378919\",\n			\"application\": \"brite:bill\"\n		},\n		{\n			\"id\": \"10313378918\",\n			\"application\": \"siebel\"\n		},\n		{\n			\"id\": \"\",\n			\"application\": \"cbs\"\n		}\n	]\n}        \n      	"
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: /v1/oauth_nl/token Get WSO2 auth token - Step 1
        x-testDescription: This API must be used to authenticate the user.
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/orders/search:
    post:
      description: >-
        Gets the product detils for the customer.


        Note:

         Please get the latest access token before sending the request using the 'Get WSO2 auth token - Step 1' service present in the same folder.
      summary: /v1/orders/search
      tags:
      - Misc
      operationId: /v1/orders/search
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/~1v1~1orders~1searchrequest'
      - name: X-Api-Key
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/~1v1~1orders~1searchresponse'
          examples:
            application/json:
              Status:
                StatusName: FAILURE
                StatusReason: No orders found
              PagingAndSorting:
                PageData:
                  PageSize: 20
                  TotalPages: 0
                  Index: 1
      security: []
      x-unitTests:
      - request:
          method: POST
          uri: /v1/orders/search
          headers:
            Content-Type: application/json
            X-Api-Key: OUGIuUc9RpSDTocY97cMbcqACdTVAPTu
            Authorization: 9f421e6e25599c53abdcede3dc35f8
          body: "{  \r\n   \"CustomerOrderSearchRequest\":{  \r\n      \"OrderHeader\":{  \r\n         \"OrderId\":\"456\",\r\n         \"Active\":\"Y\",\r\n         \"OrderType\":[  \r\n            \"MSISDN Swap Order\",\r\n            \"Sales Order\"\r\n         ],\r\n         \"OrderSubType\":\"\",\r\n         \"OrderStatus\":\"IN_PROGRESS\"\r\n      },\r\n      \"OrderItem\":{  \r\n         \"ProductType\":\"\",\r\n         \"SubStatus\":\"\",\r\n         \"Status\":\"\"\r\n      }\r\n   }\r\n}"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: RAW
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers:
            Connection: keep-alive
            Content-Length: 147
            Content-Type: application/json
            ConversationId: 3a9f9ec7-46d7-472b-813d-2a2e7166d0aa
            Date: Tue, 14 Nov 2017 14:38:01 GMT
            Server: Apigee Router
          body: '{"Status":{"StatusName":"FAILURE","StatusReason":"No orders found"},"PagingAndSorting":{"PageData":{"PageSize":"20","TotalPages":"0","Index":"1"}}}'
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: /v1/orders/search
        x-testDescription: >-
          Gets the product detils for the customer.


          Note:

           Please get the latest access token before sending the request using the 'Get WSO2 auth token - Step 1' service present in the same folder.
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  /v1/oauthNl/token get wso2 auth token - step 1response:
    title: /v1/oauth_nl/token Get WSO2 auth token - Step 1Response
    example:
      uid: 401203
      token_type: bearer
      expires_in: 2400
      refresh_token: 7bcbf7def9e2da21a4bbef6ef546e4
      access_token: 9f421e6e25599c53abdcede3dc35f8
      customer_type: 4G/LTE
      status: 200
      email: anamewpcftjgnsk16s11ptest0011@tele2.com
      role: Consumer
      msisdn: ''
      resellerShopId: ''
      applicationLinks:
      - id: 10313378919
        application: brite:bill
      - id: 10313378918
        application: siebel
      - id: ''
        application: cbs
    type: object
    properties:
      uid:
        description: ''
        type: string
      token_type:
        description: ''
        type: string
      expires_in:
        description: ''
        type: string
      refresh_token:
        description: ''
        type: string
      access_token:
        description: ''
        type: string
      customer_type:
        description: ''
        type: string
      status:
        description: ''
        type: string
      email:
        description: ''
        type: string
      role:
        description: ''
        type: string
      msisdn:
        description: ''
        type: string
      resellerShopId:
        description: ''
        type: string
      applicationLinks:
        description: ''
        type: array
        items:
          $ref: '#/definitions/ApplicationLink'
    required:
    - uid
    - token_type
    - expires_in
    - refresh_token
    - access_token
    - customer_type
    - status
    - email
    - role
    - msisdn
    - resellerShopId
    - applicationLinks
  ApplicationLink:
    title: ApplicationLink
    type: object
    properties:
      id:
        description: ''
        type: string
      application:
        description: ''
        type: string
    required:
    - id
    - application
  /v1/orders/searchrequest:
    title: /v1/orders/searchRequest
    example:
      CustomerOrderSearchRequest:
        OrderHeader:
          OrderId: 456
          Active: Y
          OrderType:
          - MSISDN Swap Order
          - Sales Order
          OrderSubType: ''
          OrderStatus: IN_PROGRESS
        OrderItem:
          ProductType: ''
          SubStatus: ''
          Status: ''
    type: object
    properties:
      CustomerOrderSearchRequest:
        $ref: '#/definitions/CustomerOrderSearchRequest'
    required:
    - CustomerOrderSearchRequest
  CustomerOrderSearchRequest:
    title: CustomerOrderSearchRequest
    type: object
    properties:
      OrderHeader:
        $ref: '#/definitions/OrderHeader'
      OrderItem:
        $ref: '#/definitions/OrderItem'
    required:
    - OrderHeader
    - OrderItem
  OrderHeader:
    title: OrderHeader
    type: object
    properties:
      OrderId:
        description: ''
        type: string
      Active:
        description: ''
        type: string
      OrderType:
        description: ''
        type: array
        items:
          type: string
      OrderSubType:
        description: ''
        type: string
      OrderStatus:
        description: ''
        type: string
    required:
    - OrderId
    - Active
    - OrderType
    - OrderSubType
    - OrderStatus
  OrderItem:
    title: OrderItem
    type: object
    properties:
      ProductType:
        description: ''
        type: string
      SubStatus:
        description: ''
        type: string
      Status:
        description: ''
        type: string
    required:
    - ProductType
    - SubStatus
    - Status
  /v1/orders/searchresponse:
    title: /v1/orders/searchResponse
    example:
      Status:
        StatusName: FAILURE
        StatusReason: No orders found
      PagingAndSorting:
        PageData:
          PageSize: 20
          TotalPages: 0
          Index: 1
    type: object
    properties:
      Status:
        $ref: '#/definitions/Status'
      PagingAndSorting:
        $ref: '#/definitions/PagingAndSorting'
    required:
    - Status
    - PagingAndSorting
  Status:
    title: Status
    type: object
    properties:
      StatusName:
        description: ''
        type: string
      StatusReason:
        description: ''
        type: string
    required:
    - StatusName
    - StatusReason
  PagingAndSorting:
    title: PagingAndSorting
    type: object
    properties:
      PageData:
        $ref: '#/definitions/PageData'
    required:
    - PageData
  PageData:
    title: PageData
    type: object
    properties:
      PageSize:
        description: ''
        type: string
      TotalPages:
        description: ''
        type: string
      Index:
        description: ''
        type: string
    required:
    - PageSize
    - TotalPages
    - Index
