swagger: '2.0'
info:
  version: '1.0'
  title: orders_v1
  description: >
    Collection to test orders_v1 API Proxy

    Consumer: My Tele2 NL

    Provider: TIP; Siebel_NL
  contact: {}
host: api.tele2.com:9006
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /nl/v1/oauth_nl/token:
    post:
      description: This API must be used to authenticate the user.
      summary: /v1/oauth_nl/token Get WSO2 auth token - Step 1
      tags:
      - Misc
      operationId: NlV1OauthNlTokenPost
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: X-Api-Key
        in: header
        required: true
        type: string
        description: Authorization from calling system
      - name: Content-Type
        in: header
        required: true
        type: string
        description: The value should be 'application/x-www-form-urlencoded'
      - name: client_id
        in: formData
        required: true
        type: string
        description: This field requires to have client id, this should be requested and provide by appigee/WSO2
      - name: client_secret
        in: formData
        required: true
        type: string
        description: This field requires to have client secret, this should be requested and provide by appigee/WSO2.
      - name: grant_type
        in: formData
        required: true
        type: string
        description: The values that can be send in this field is 'refresh_token' or 'password'.
      - name: username
        in: formData
        required: true
        type: string
        description: This field should contain the username. It is required when the grant type is password.
      - name: password
        in: formData
        required: true
        type: string
        description: This field should contain the password. It is required when the grant type is password.
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/GetWSO2authtokenOK'
          examples:
            application/json:
              uid: 401203
              token_type: bearer
              expires_in: 2400
              refresh_token: 7bcbf7def9e2da21a4bbef6ef546e4
              access_token: 9f421e6e25599c53abdcede3dc35f8
              customer_type: 4G/LTE
              status: 200
              email: anamewpcftjgnsk16s11ptest0011@tele2.com
              role: Consumer
              msisdn: ''
              resellerShopId: ''
              applicationLinks:
              - id: 10313378919
                application: brite:bill
              - id: 10313378918
                application: siebel
              - id: ''
                application: cbs
          headers:
            Access-Control-Allow-Headers:
              type: string
              default: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction
            Access-Control-Allow-Methods:
              type: string
              default: DELETE,POST,PUT,GET
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Cache-Control:
              type: string
              default: no-cache, no-store, max-age=0, must-revalidate
            Connection:
              type: string
              default: keep-alive
            Date:
              type: string
              default: Tue, 14 Nov 2017 14:43:44 GMT
            Expires:
              type: string
              default: 0
            Pragma:
              type: string
              default: no-cache
            Server:
              type: string
              default: WSO2-PassThrough-HTTP
            Transfer-Encoding:
              type: string
              default: chunked
            X-Application-Context:
              type: string
              default: application:uat:6060
            X-Content-Type-Options:
              type: string
              default: nosniff
            X-Frame-Options:
              type: string
              default: SAMEORIGIN
            X-XSS-Protection:
              type: string
              default: 1; mode=block
  /v1/orders/search:
    post:
      description: >-
        Gets the product detils for the customer.


        Note:

         Please get the latest access token before sending the request using the 'Get WSO2 auth token - Step 1' service present in the same folder.
      summary: /v1/orders/search
      tags:
      - Misc
      operationId: V1OrdersSearchPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: X-Api-Key
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: Token from outh request
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/~1v1~1orders~1searchrequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Noordersfoundbusinessexception'
          examples:
            application/json:
              Status:
                StatusName: FAILURE
                StatusReason: No orders found
              PagingAndSorting:
                PageData:
                  PageSize: 20
                  TotalPages: 0
                  Index: 1
          headers:
            Connection:
              type: string
              default: keep-alive
            Content-Length:
              type: string
              default: 147
            ConversationId:
              type: string
              default: 3a9f9ec7-46d7-472b-813d-2a2e7166d0aa
            Date:
              type: string
              default: Tue, 14 Nov 2017 14:38:01 GMT
            Server:
              type: string
              default: Apigee Router
definitions:
  GetWSO2authtokenOK:
    title: GetWSO2authtokenOK
    example:
      uid: 401203
      token_type: bearer
      expires_in: 2400
      refresh_token: 7bcbf7def9e2da21a4bbef6ef546e4
      access_token: 9f421e6e25599c53abdcede3dc35f8
      customer_type: 4G/LTE
      status: 200
      email: anamewpcftjgnsk16s11ptest0011@tele2.com
      role: Consumer
      msisdn: ''
      resellerShopId: ''
      applicationLinks:
      - id: 10313378919
        application: brite:bill
      - id: 10313378918
        application: siebel
      - id: ''
        application: cbs
    type: object
    properties:
      uid:
        type: string
      token_type:
        type: string
      expires_in:
        type: string
      refresh_token:
        type: string
      access_token:
        type: string
      customer_type:
        type: string
      status:
        type: string
      email:
        type: string
      role:
        type: string
      msisdn:
        type: string
      resellerShopId:
        type: string
      applicationLinks:
        type: array
        items:
          $ref: '#/definitions/ApplicationLink'
    required:
    - uid
    - token_type
    - expires_in
    - refresh_token
    - access_token
    - customer_type
    - status
    - email
    - role
    - msisdn
    - resellerShopId
    - applicationLinks
  ApplicationLink:
    title: ApplicationLink
    example:
      id: 10313378919
      application: brite:bill
    type: object
    properties:
      id:
        type: string
      application:
        type: string
    required:
    - id
    - application
  /v1/orders/searchrequest:
    title: /v1/orders/searchrequest
    example:
      CustomerOrderSearchRequest:
        OrderHeader:
          OrderId: 456
          Active: Y
          OrderType:
          - MSISDN Swap Order
          - Sales Order
          OrderSubType: ''
          OrderStatus: IN_PROGRESS
        OrderItem:
          ProductType: ''
          SubStatus: ''
          Status: ''
    type: object
    properties:
      CustomerOrderSearchRequest:
        $ref: '#/definitions/CustomerOrderSearchRequest'
    required:
    - CustomerOrderSearchRequest
  CustomerOrderSearchRequest:
    title: CustomerOrderSearchRequest
    example:
      OrderHeader:
        OrderId: 456
        Active: Y
        OrderType:
        - MSISDN Swap Order
        - Sales Order
        OrderSubType: ''
        OrderStatus: IN_PROGRESS
      OrderItem:
        ProductType: ''
        SubStatus: ''
        Status: ''
    type: object
    properties:
      OrderHeader:
        $ref: '#/definitions/OrderHeader'
      OrderItem:
        $ref: '#/definitions/OrderItem'
    required:
    - OrderHeader
    - OrderItem
  OrderHeader:
    title: OrderHeader
    example:
      OrderId: 456
      Active: Y
      OrderType:
      - MSISDN Swap Order
      - Sales Order
      OrderSubType: ''
      OrderStatus: IN_PROGRESS
    type: object
    properties:
      OrderId:
        type: string
      Active:
        type: string
      OrderType:
        type: array
        items:
          type: string
      OrderSubType:
        type: string
      OrderStatus:
        type: string
    required:
    - OrderId
    - Active
    - OrderType
    - OrderSubType
    - OrderStatus
  OrderItem:
    title: OrderItem
    example:
      ProductType: ''
      SubStatus: ''
      Status: ''
    type: object
    properties:
      ProductType:
        type: string
      SubStatus:
        type: string
      Status:
        type: string
    required:
    - ProductType
    - SubStatus
    - Status
  Noordersfoundbusinessexception:
    title: Noordersfoundbusinessexception
    example:
      Status:
        StatusName: FAILURE
        StatusReason: No orders found
      PagingAndSorting:
        PageData:
          PageSize: 20
          TotalPages: 0
          Index: 1
    type: object
    properties:
      Status:
        $ref: '#/definitions/Status'
      PagingAndSorting:
        $ref: '#/definitions/PagingAndSorting'
    required:
    - Status
    - PagingAndSorting
  Status:
    title: Status
    example:
      StatusName: FAILURE
      StatusReason: No orders found
    type: object
    properties:
      StatusName:
        type: string
      StatusReason:
        type: string
    required:
    - StatusName
    - StatusReason
  PagingAndSorting:
    title: PagingAndSorting
    example:
      PageData:
        PageSize: 20
        TotalPages: 0
        Index: 1
    type: object
    properties:
      PageData:
        $ref: '#/definitions/PageData'
    required:
    - PageData
  PageData:
    title: PageData
    example:
      PageSize: 20
      TotalPages: 0
      Index: 1
    type: object
    properties:
      PageSize:
        type: string
      TotalPages:
        type: string
      Index:
        type: string
    required:
    - PageSize
    - TotalPages
    - Index
tags:
- name: Misc
  description: ''
